compatibility.bs
=> Fix #15: -webkit-device-pixel-radius value is <<number>>

.editorconfig, .gitattributes, .pr-preview.json
See https://github.com/whatwg/meta/issues/16.
=> Meta: enable PR preview

.gitignore, Makefile, README.md
Broken by https://github.com/whatwg/compat/pull/82.
=> Meta: fix the README about local deploy to actually work

LICENSE, compatibility.bs
Also cleans up some anchors and RFC 2119 usage.
---
Do not merge until https://github.com/tabatkins/bikeshed/pull/1155 is merged
=> Meta: use new WHATWG boilerplate and license

compatibility.bs
***
<a href="https://whatpr.org/compat/130.html" title="Last updated on Sep 29, 2020, 2:47 PM UTC (19220e2)">Preview</a> | <a href="https://whatpr.org/compat/130/dbc4b85...19220e2.html" title="Last updated on Sep 29, 2020, 2:47 PM UTC (19220e2)">Diff</a>
=> Meta: link Review Draft

compatibility.bs
Just updating my email (6 months late...)
***
<a href="https://whatpr.org/compat/142.html" title="Last updated on Mar 22, 2021, 9:56 PM UTC (3e5bfe4)">Preview</a> | <a href="https://whatpr.org/compat/142/dde80c6...3e5bfe4.html" title="Last updated on Mar 22, 2021, 9:56 PM UTC (3e5bfe4)">Diff</a>
=> No issue - Update Mike's email address and affiliation

uastring/minutes/index.md
This is creating the placeholder for where we will be working around the UA string reduction topic.
=> Issue #146 - Adds UA String Reduction Minutes Index

compatibility.bs
PTAL, @zcorpan - thanks!
***
<a href="https://whatpr.org/compat/155.html" title="Last updated on Aug 6, 2021, 5:12 PM UTC (dd9aa8a)">Preview</a> | <a href="https://whatpr.org/compat/155/2c0b530...dd9aa8a.html" title="Last updated on Aug 6, 2021, 5:12 PM UTC (dd9aa8a)">Diff</a>
=> Fixes #121 - Use legacy name alias concept as defined by CSS

uastring/README.md, uastring/minutes/2021-11-03-minutes.md, uastring/minutes/index.md
=> Meta:  Adds 2021-11-03 UA String Minutes

uastring/minutes/2021-12-01-minutes.md
Minutes from last meeting.
r? @karlcow
=> Meta: Add Dec 1, 2021 meeting minutes

compatibility.bs
Fixes: #172
***
<a href="https://whatpr.org/compat/178.html" title="Last updated on Feb 5, 2022, 12:16 AM UTC (0bd9a7f)">Preview</a> | <a href="https://whatpr.org/compat/178/e9c0004...0bd9a7f.html" title="Last updated on Feb 5, 2022, 12:16 AM UTC (0bd9a7f)">Diff</a>
=> Editorial: don't treat frozen constants as tokens

compatibility.bs
Closes #170
(doing this exercise made me see a few areas to be improved - hopefully find time for that this week).
PTAL, @karlcow
***
<a href="https://whatpr.org/compat/179.html" title="Last updated on Feb 15, 2022, 10:30 PM UTC (f45cb25)">Preview</a> | <a href="https://whatpr.org/compat/179/632af7f...f45cb25.html" title="Last updated on Feb 15, 2022, 10:30 PM UTC (f45cb25)">Diff</a>
=> Editorial: Highlight values that change in UA string examples

uastring/minutes/2021-10-05-minutes.md, uastring/minutes/2022-01-05-minutes.md, uastring/minutes/2022-02-02-minutes.md, uastring/minutes/index.md
Hi mike these are the missing minutes.
=> Meta: Adds UA string minutes for January and February 2022

compatibility.bs
Fixes #184
PTAL @domenic
***
<a href="https://whatpr.org/compat/185.html" title="Last updated on Mar 9, 2022, 9:22 PM UTC (0cf5b53)">Preview</a> | <a href="https://whatpr.org/compat/185/ab11250...0cf5b53.html" title="Last updated on Mar 9, 2022, 9:22 PM UTC (0cf5b53)">Diff</a>
=> Replace usage of responsible document

compatibility.bs
And link a few unlinked things. But no normative changes.
r? @karlcow
***
<a href="https://whatpr.org/compat/186.html" title="Last updated on Mar 19, 2022, 12:25 AM UTC (fbbd6d8)">Preview</a> | <a href="https://whatpr.org/compat/186/678d923...fbbd6d8.html" title="Last updated on Mar 19, 2022, 12:25 AM UTC (fbbd6d8)">Diff</a>
=> Editorial: Line wrapping and edits for clarity

compatibility.bs
Fixes #180. 
PTAL @karlcow
***
<a href="https://whatpr.org/compat/187.html" title="Last updated on Mar 28, 2022, 9:22 PM UTC (8545c0b)">Preview</a> | <a href="https://whatpr.org/compat/187/ad8889a...8545c0b.html" title="Last updated on Mar 28, 2022, 9:22 PM UTC (8545c0b)">Diff</a>
=> Add a <safariPlatform> token.

uastring/minutes/2022-03-02-minutes.md, uastring/minutes/2022-04-06-minutes.md, uastring/minutes/index.md
=> Chore: add March and April UA string meeting minutes

uastring/README.md
Fixes #191 (thanks for filing @karlcow)
=> Editorial: fix broken link

compatibility.bs
Fixes #197.
This is the default for version 101 and above. See:
https://www.chromium.org/updates/ua-reduction/
https://chromiumdash.appspot.com/commit/3fea2402264010af295c8dd87400368680100228
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 17, 2022, 9:41 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwhatpr.org%2Fcompat%2F198%2Fdbc61f1.html&doc2=https%3A%2F%2Fwhatpr.org%2Fcompat%2F198.html)
``` …
```
=> Specify Chrome "minor version reduction"

uastring/minutes/2022-06-24-minutes.md, uastring/minutes/index.md
=> meta: Add June 2022 UA meeting minutes

compatibility.bs
Fixes #204 
PTAL @karlcow
***
<a href="https://whatpr.org/compat/205.html" title="Last updated on Jul 1, 2022, 7:57 PM UTC (d244c38)">Preview</a> | <a href="https://whatpr.org/compat/205/c75f0ee...d244c38.html" title="Last updated on Jul 1, 2022, 7:57 PM UTC (d244c38)">Diff</a>
=> Add reduced MINOR.BUILD.PATCH to Chrome pattern

compatibility.bs
Fixes #207 
We should land this before https://github.com/whatwg/compat/pull/209
r? @karlcow
***
<a href="https://whatpr.org/compat/210.html" title="Last updated on Jul 31, 2022, 11:26 PM UTC (cb92bf0)">Preview</a> | <a href="https://whatpr.org/compat/210/9d76a8f...cb92bf0.html" title="Last updated on Jul 31, 2022, 11:26 PM UTC (cb92bf0)">Diff</a>
=> Define "decompose" and "constant" (#207)

compatibility.bs
Fixes #188 
r? @karlcow
***
<a href="https://whatpr.org/compat/209.html" title="Last updated on Aug 1, 2022, 5:29 PM UTC (fb3082c)">Preview</a> | <a href="https://whatpr.org/compat/209/e450ea5...fb3082c.html" title="Last updated on Aug 1, 2022, 5:29 PM UTC (fb3082c)">Diff</a>
=> Improve Safari User-Agent patterns (#188)

compatibility.bs
r? @karlcow
***
<a href="https://whatpr.org/compat/216.html" title="Last updated on Oct 14, 2022, 12:48 AM UTC (07aa8c5)">Preview</a> | <a href="https://whatpr.org/compat/216/7fc0fd8...07aa8c5.html" title="Last updated on Oct 14, 2022, 12:48 AM UTC (07aa8c5)">Diff</a>
=> Meta: disambiguate "animation-delay"

compatibility.bs
Fixes #221.
***
<a href="https://whatpr.org/compat/222.html" title="Last updated on Nov 10, 2022, 3:26 AM UTC (0c5d5b5)">Preview</a> | <a href="https://whatpr.org/compat/222/c61bfe4...0c5d5b5.html" title="Last updated on Nov 10, 2022, 3:26 AM UTC (0c5d5b5)">Diff</a>
=> Define `-webkit-transform-3d` with `Type: discrete`

uastring/minutes/2022-08-19-minutes.md, uastring/minutes/2022-10-14-minutes.md, uastring/minutes/2022-11-18-minutes.md, uastring/minutes/2022-12-16-minutes.md
Minutes for August, October, November, and December meetings. No meeting happened in September, but I don't remember why.
=> Meta: add some missing meeting minutes

uastring/minutes/index.md
=> Meta: Update uastring minutes index

uastring/minutes/2023-02-24-minutes.md, uastring/minutes/index.md
=> Editorial: add minutes for 2023-02-24 meeting

compatibility.bs
***
<a href="https://whatpr.org/compat/236.html" title="Last updated on Mar 27, 2023, 2:42 PM UTC (513b1d5)">Preview</a> | <a href="https://whatpr.org/compat/236/80bf34b...513b1d5.html" title="Last updated on Mar 27, 2023, 2:42 PM UTC (513b1d5)">Diff</a>
=> Meta: export deviceCompat dfn

compatibility.bs
***
<a href="https://whatpr.org/compat/277.html" title="Last updated on Jul 19, 2025, 6:27 AM UTC (2dc03cf)">Preview</a> | <a href="https://whatpr.org/compat/277/1623a6a...2dc03cf.html" title="Last updated on Jul 19, 2025, 6:27 AM UTC (2dc03cf)">Diff</a>
=> Meta: link Simplified Chinese translation
