whatwg/compat

compatibility.bs
Typo: -webkit-border-top-left-radius currently map to border-top-right-radius instead of border-top-left-radius
=> -webkit-border-top-left-radius should not map to to border-top-right-radius

compatibility.bs, compatibility.html
Fixes #68
Preview [here](https://rawgit.com/RByers/compat/touch-action-pinch-zoom/compatibility.html#css-property-values)
/cc @dtapuska @mustaqahmed @staktrace
@miketaylr my Bikeshed-foo is weak, feel free to suggest improvements.  Also note that there are some subtle details about `pinch-zoom` semantics and complexities in the `touch-action` processing model that make this pretty hard to explain super rigorously.  My plan here is to focus on getting standard automated input testing working in `web-platform-test` so we can describe exactly what we mean in tests, while continuing to tweak spec text to be more precise.
=> Add touch-action pinch-zoom value

compatibility.bs
A few other specs that have something similar:
https://fetch.spec.whatwg.org/
https://w3c.github.io/IndexedDB/
https://notifications.spec.whatwg.org/
https://xhr.spec.whatwg.org/
Unlike those specs, there's no label in wpt for compat, so no
"ongoing work" link was added.
=> Add a link to web-platform-tests to the top of the spec

README.md
Currently, the linefeed is not rendered as a newline on GitHub.
I'm also OK with changing it to an ordered list in Markdown syntax if it's preferred (although it won't be 0-indexed any more).
=> Meta: Markup fix in README.md

compatibility.bs
Be more consistent with other WHATWG specs, since they usually refer to the editor's draft.
Also fixed a broken link (`#descdef-resolution` in MQ), removed an unused anchor ("calculated values" in css3-values), and changed some links from HTTP to HTTPS.
=> More HTTPS and ED links

compatibility.bs
Also say that appearance must not be supported.
=> Say that -webkit-appearance must be supported

compatibility.bs
This maintains the id it had, but fixes the link text to be the expected name of the property
[editorial]
***
<a href="https://whatpr.org/compat/134.html" title="Last updated on Dec 16, 2020, 5:08 PM UTC (0505050)">Preview</a> | <a href="https://whatpr.org/compat/134/c0f5a5a...0505050.html" title="Last updated on Dec 16, 2020, 5:08 PM UTC (0505050)">Diff</a>
=> Fix <dfn> of -webkit-flex

compatibility.bs
(not inline style)
In theory bikeshed should like this more.
***
<a href="https://whatpr.org/compat/149.html" title="Last updated on Jun 2, 2021, 5:21 PM UTC (96e0585)">Preview</a> | <a href="https://whatpr.org/compat/149/c66385f...96e0585.html" title="Last updated on Jun 2, 2021, 5:21 PM UTC (96e0585)">Diff</a>
=> Fixes #148 - Declare img width and height using attributes

compatibility.bs
This is a <s>WIP</s> change that adds a User-Agent string section. The goal is to document current UA string patterns for Chrome, Firefox, and Safari, and highlight where things are frozen perhaps. 
Early draft text lives at https://docs.google.com/document/d/1LFFl_N473aAibZzosvvKmX2OGwaZgW5dmRTE2j9nUgw/edit#, and I need to finish moving over the UA strings and fix some links. Hopefully that won't take too long.
cc @karlcow
***
<a href="https://whatpr.org/compat/166.html" title="Last updated on Feb 1, 2022, 3:39 PM UTC (076efb6)">Preview</a> | <a href="https://whatpr.org/compat/166/07c590e...076efb6.html" title="Last updated on Feb 1, 2022, 3:39 PM UTC (076efb6)">Diff</a>
=> Add a User-Agent String section

compatibility.bs
PTAL @karlcow
***
<a href="https://whatpr.org/compat/175.html" title="Last updated on Feb 2, 2022, 12:12 AM UTC (6442fb6)">Preview</a> | <a href="https://whatpr.org/compat/175/3ca5920...6442fb6.html" title="Last updated on Feb 2, 2022, 12:12 AM UTC (6442fb6)">Diff</a>
=> Editorial: Fix Safari UA example & add quotes to strings

compatibility.bs
As used universally everywhere else in the spec.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/compat/176.html" title="Last updated on Feb 3, 2022, 1:43 AM UTC (4d4e8af)">Preview</a> | <a href="https://whatpr.org/compat/176/ec26d28...4d4e8af.html" title="Last updated on Feb 3, 2022, 1:43 AM UTC (4d4e8af)">Diff</a>
=> Editorial: Add leading dash to`-webkit-`

compatibility.bs
And address most of the other feedback from #182. Will tackle the rest in #180.
Fixes #182.
***
<a href="https://whatpr.org/compat/183.html" title="Last updated on Mar 7, 2022, 10:32 PM UTC (34288f8)">Preview</a> | <a href="https://whatpr.org/compat/183/0f44e24...34288f8.html" title="Last updated on Mar 7, 2022, 10:32 PM UTC (34288f8)">Diff</a>
=> Add missing "(KHTML, like Gecko)" to Safari and Chrome patterns

compatibility.bs
Similar to Safari, this differentiates between mobile and
desktop. In #174, we can further improve this by defining
the allowed values for <platform> and <oscpu>, etc.
Closes #171
PTAL @karlcow
***
<a href="https://whatpr.org/compat/190.html" title="Last updated on May 2, 2022, 6:28 PM UTC (26665de)">Preview</a> | <a href="https://whatpr.org/compat/190/609c205...26665de.html" title="Last updated on May 2, 2022, 6:28 PM UTC (26665de)">Diff</a>
=> Improve Firefox UA pattern on desktop and mobile

compatibility.bs
This fixes the spec tests to be aligned with the reality as described in the issue #195 
There is no need for special treatment.
***
<a href="https://whatpr.org/compat/196.html" title="Last updated on Jun 17, 2022, 1:14 AM UTC (16bd486)">Preview</a> | <a href="https://whatpr.org/compat/196/4aa38ed...16bd486.html" title="Last updated on Jun 17, 2022, 1:14 AM UTC (16bd486)">Diff</a>
=> Fix #195. Make -webkit-background-clip an alias of background-clip.

compatibility.bs
This is done by introducing a <chromePlatform> token, similar to
the existing <firefoxPlatform> token, which allows us to differentiate
between desktop and mobile in the Chrome-specific tokens section.
Fixes #199
PTAL @karlcow
***
<a href="https://whatpr.org/compat/206.html" title="Last updated on Jul 6, 2022, 7:46 PM UTC (e6b0621)">Preview</a> | <a href="https://whatpr.org/compat/206/4c491df...e6b0621.html" title="Last updated on Jul 6, 2022, 7:46 PM UTC (e6b0621)">Diff</a>
=> Document <deviceModel> for Chrome for Android

compatibility.bs
Fix #214.  See the comment about  the broken reference.
Hmm Should I put editorial in there?
***
<a href="https://whatpr.org/compat/215.html" title="Last updated on Oct 14, 2022, 1:14 AM UTC (c765c7f)">Preview</a> | <a href="https://whatpr.org/compat/215/dd67fc2...c765c7f.html" title="Last updated on Oct 14, 2022, 1:14 AM UTC (c765c7f)">Diff</a>
=> Meta: fix #214 - Removes the broken ref to animation type

compatibility.bs
This an editorial change.
*The <shorthand-name> property is a shorthand for ...* is a canonical sentence often used in CSS specs, which is followed by the names of its sub-properties, therefore the current text is ambiguous because it links to the SVG 2 spec and suggests that this spec defines its sub-properties.
***
<a href="https://whatpr.org/compat/232.html" title="Last updated on Feb 27, 2023, 4:14 PM UTC (69f6e6e)">Preview</a> | <a href="https://whatpr.org/compat/232/e23a6e7...69f6e6e.html" title="Last updated on Feb 27, 2023, 4:14 PM UTC (69f6e6e)">Diff</a>
=> Define -webkit-text-stroke sub-properties

compatibility.bs
This introduces a new "<unifiedPlatform>" that we can hook the mobile UA pattern into once Phase 6 is landed.
Fixes #233
***
<a href="https://whatpr.org/compat/235.html" title="Last updated on Feb 27, 2023, 11:22 PM UTC (4598fc4)">Preview</a> | <a href="https://whatpr.org/compat/235/95345b9...4598fc4.html" title="Last updated on Feb 27, 2023, 11:22 PM UTC (4598fc4)">Diff</a>
=> Document Chrome's Phase 5 of UA Reduction

compatibility.bs
The old algorithm we got the angle from ScreenOrientation no longer exists, so instead we get the "current orientation angle". But this is a no-op refactor - the result is the same.
Fixes #223
***
<a href="https://whatpr.org/compat/241.html" title="Last updated on Apr 20, 2023, 8:13 PM UTC (1af86db)">Preview</a> | <a href="https://whatpr.org/compat/241/bfbbfe0...1af86db.html" title="Last updated on Apr 20, 2023, 8:13 PM UTC (1af86db)">Diff</a>
=> Editorial: refactor getting the window.orientation angle

compatibility.bs
This allows us to remove some no longer needed
Chrome-specific tokens.
PTAL @karlcow
***
<a href="https://whatpr.org/compat/243.html" title="Last updated on May 18, 2023, 8:19 PM UTC (34a8c7d)">Preview</a> | <a href="https://whatpr.org/compat/243/59340d0...34a8c7d.html" title="Last updated on May 18, 2023, 8:19 PM UTC (34a8c7d)">Diff</a>
=> Document Chrome's Phase 6 of UA Reduction

review-drafts/2023-06.bs
The [June 2023 Review Draft](https://compat.spec.whatwg.org/review-drafts/2023-06/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/compat/244.html" title="Last updated on Jun 19, 2023, 9:04 AM UTC (47b1617)">Preview</a> | <a href="https://whatpr.org/compat/244/404bb17...47b1617.html" title="Last updated on Jun 19, 2023, 9:04 AM UTC (47b1617)">Diff</a>
=> Review Draft Publication: June 2023

compatibility.bs
Fixes #250
***
<a href="https://whatpr.org/compat/251.html" title="Last updated on Sep 27, 2023, 5:06 PM UTC (91e628b)">Preview</a> | <a href="https://whatpr.org/compat/251/5f87ba7...91e628b.html" title="Last updated on Sep 27, 2023, 5:06 PM UTC (91e628b)">Diff</a>
=> Meta: Add 'box-shadow' and 'border-radius' to link-defaults

compatibility.bs
Bikeshed'll start complaining about this in the next release, since it's a parse error.
***
<a href="https://whatpr.org/compat/256.html" title="Last updated on Dec 8, 2023, 10:45 PM UTC (c08d977)">Preview</a> | <a href="https://whatpr.org/compat/256/30d5c35...c08d977.html" title="Last updated on Dec 8, 2023, 10:45 PM UTC (c08d977)">Diff</a>
=> Fix invalid character escape

compatibility.bs
Fixes #259
***
<a href="https://whatpr.org/compat/260.html" title="Last updated on Dec 18, 2023, 4:41 PM UTC (5830c71)">Preview</a> | <a href="https://whatpr.org/compat/260/57c7631...5830c71.html" title="Last updated on Dec 18, 2023, 4:41 PM UTC (5830c71)">Diff</a>
=> Meta: fix border-bottom-* and border-top-* linking errors

compatibility.bs
Fixes #273
***
<a href="https://whatpr.org/compat/274.html" title="Last updated on Jul 24, 2025, 8:33 PM UTC (6dcf6f6)">Preview</a> | <a href="https://whatpr.org/compat/274/521d522...6dcf6f6.html" title="Last updated on Jul 24, 2025, 8:33 PM UTC (6dcf6f6)">Diff</a>
=> Meta: override default issue class to display GitHub issue links
